dist: Xenial
sudo: false
group: deprecated-2017Q4
language: node_js
node_js:
  - "10"
python:
  - 3.4
before_install:
# - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
# - sudo service docker restart
- |
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.md$' || {
      echo "Only docs were updated, stopping build process."
      exit
    }
    sudo apt-get -y install unzip
    sudo apt-get -y install wget
    sudo apt-get -y install python3-pip python-dev
install:
  - sudo pip3 install requests
jobs:
  include:
  - name: "Check Header"
    env: TEST=check_header
  - name: "Unit Test"
    env: TEST=unit_test
  - name: "Code Scan"
    env: TEST=code_scan
  - name: "Smoke Test"
    env: TEST=smoke_test
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script: >
  if [ x${TEST} = xcheck_header ]; then
    git clone --branch=devops https://github.com/kevinchcn/data-annotator-for-machine-learning.git devops
    echo $TRAVIS_BUILD_DIR
    cp $TRAVIS_BUILD_DIR/devops/check_headers.py .
    chmod +x check_headers.py
    python3 ./check_headers.py -f "$(git diff --name-only --diff-filter=d $TRAVIS_COMMIT_RANGE)"
  fi &&
  if [ x${TEST} = xunit_test ]; then
    echo unit test Start
    echo unit test
    echo unit test End
  fi &&
  if [ x${TEST} = xcode_scan ]; then
    echo Scan Start
    echo Scan End
  fi &&
  if [ x${TEST} = xsmoke_test ]; then
    sudo sh -c 'echo "\n::1 localhost\n" >> /etc/hosts'
    cat /etc/hosts
    echo ls 1
    ls -l 
    cat annotation-service/app-os.js
    git clone --branch=devops https://github.com/kevinchcn/data-annotator-for-machine-learning.git devops
    echo ls 2
    ls -l
    echo $TRAVIS_BUILD_DIR
    cp -r $TRAVIS_BUILD_DIR/devops/* .
    echo ls 3
    ls -l 
    cat annotation-service/app-os.js
    chmod +x annotation-app/docker-entrypoint.sh
    cat annotation-service/app-os.js
    docker-compose up -d
    docker-compose ps
    echo netstat
    docker-compose version
    netstat -tulpen
    echo Curl Start 1
    docker exec -it e2e curl -X PUT -H "Content-Type: application/json" -d '{"email":"joeq@vmware.com","password":"password","uname":"Joe K Qiao"}' service:3000/api/v1.0/register
    echo Curl End 1
    echo Curl Start 2
    docker exec -it e2e curl -X POST -H "Content-Type: application/json" -d '{"email":"joeq@vmware.com","password":"password"}' service:3000/api/v1.0/login
    echo Curl End 2
    echo Curl Start 3
    curl -X PUT -H "Content-Type: application/json" -d '{"email":"joeq@vmware.com","password":"password","uname":"Joe K Qiao"}' http://127.0.0.1:3000/api/v1.0/register
    echo Curl End 3
    echo Curl Start 4
    curl -X PUT -6 -H "Content-Type: application/json" -d '{"email":"joeq@vmware.com","password":"password","uname":"Joe K Qiao"}' http://localhost:3000/api/v1.0/register
    echo Curl End 4
    docker logs -f service
    echo Smoke Test Start
    cd autotest
    npm install
    npm run webdriver
    npm run e2e
    echo Smoke Test End
  fi
